language: node_js
node_js:
 - "node"
 # Build all branches, *including* gh-pages:
branches:
  only:
  - gh-pages
  - /.*/
notifications:
  webhooks:
    urls:
      - https://webhook.atomist.com/atomist/travis/teams/ABLBDC4BI
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
